### PR TITLE
Add NixOS

### PR DESCRIPTION
**Pull request by pterror**
:3

need arch user to confirm `NAME` in `/etc/os-release`

flake status: i forgot to add default.nix :skull: 

- add nix support
- fix colors for rainbow flag
- add cli flags for configuration. exact arg names are open to bikeshedding

### CODE REVIEW

**Comment by rosymati** [comment]
Thank you for your contribution. While I am not deeply familiar with Nix, I will proceed with the assumption that your changes are appropriate.
image
Here is the output of os-release on my system. I believe this should be consistent across all Arch installations.

I will test this pr and ensure it still functions properly on arch.

**Comment by pterror** [comment]
here's an example `/etc/os-release` on nixos for posterity. nixos changes are currently broken so i will be force pushing fixes (to nix code only) later
```sh
ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20240719.1d9c2c9"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"
```

**Comment by rosymati** [comment]
Tested and it works fine on arch. If you think nix support will take time I could merge this and you can work on that on another pr. That way I can keep working from the clap changes

**Comment by pterror** [comment]
flake just finished building successfully! (and the installed executable works, of course)

**Pull request merged**
